# pip install google-play-scraper


from google_play_scraper import app

result = app(
    'com.chess',
    lang='en', # defaults to 'en'
    country='us' # defaults to 'us'
)



comment_list = result['comments']
print(len(comment_list))# 40
print(comment_list)

'''
['A COMPLETE WASTE of time I wish I could give zero stars here is the "lesson" I learned , if you get the advantage the game will go to a draw in a couple of moves (even if you have checkmate) but if the computer gets an advantage it will get dozens of moves. Devs response shows they don\'t even read these. Why would I write to you , i have been very clear in my post as to the problem with this game',
 'If I\'m being honest it\'s an overrated chess game it\'s literally what you\'d expect from any chess app, just chess. Unfortunately there are no casual chess games without time limits and while your games probably won\'t go over an hour ever it is a bit annoying. It\'s about the same as every other chess game out there except there of course is "premium" which is just a dumb cash grab so don\'t buy it, isn\'t worth it in the slightest.',
 'Without a doubt the best Chess App there is! You can play "Daily" games with your friends where you can take your turn whenever you have time and wait for your opponent to make their move. There are also all kinds of Puzzles, Analysis\', and Lessons to help you improve. Has a Pass and Play feature, and you can even customize your pieces, backgrounds, and sounds. All you\'ll need in one app with no ads!!!',
 'Great app. Many flexible options to accommodate whatever availability you have to play, learn or improve. I started so that I could play a friend online, but love many other features, especially the analysis that really helps you to improve. I have only one gripe, which is that you can accidentally start a game, touch screens being what they are, and there\'s no "confirm"/ "are you sure?" step.',
 "I mostly play on the web, but this app comes in handy when I want to play a quick game or two or review my games while I'm on the go. Possible (easy) feature request: When you load a game and want to go over it from the beginning, it looks like you need to click the back button as many times as the moves of the game, or slide the move list to the beginning (unless I've missed something??) . But both of these are quite annoying to do each time. Perhaps a button to go to the starting position?",
 "The ability to customize your board is something that's greatly appreciated, the movement is awesome and if your on the phone moving faster is an option, by selecting a peace and if you know what's going to happen you can pree move your peace, although I will say you'd want to be careful with this. other then that. the app doesn't take up that many resources and is light weight on any kind of phone, if you want to play chess this is the application to do so.",
 "If you searching for a good chess app you come to the right place. this app have a lot of good features. like lesson, puzzle, tournament, articles, leaderboard, and many things involved to chess. Even though i haven't try all the features yet, but i know this thing is an amazing one. a BIG 5 STAR. (anyway hope that they will make this game into a windows game :D)",
 'fun game but people can have very bad sportsmanship on here. some people when they know they will lose, will just run the time out so you have to wait 5 minutes for the game to be over. quite annoying and a waste of time. I try to report the people who do it but it never seems like it helps...',
 "The best features of this app require a tiered subscription with absurd limits on how many two minute lesson videos you can watch on one of the tiers in a week (it's three). It's a bit silly given how short these videos are and how they are essentially charging for information you can look up yourself. The post-game analysis feature is very nice to have and it even suggests relevant tutorial videos to watch (if you haven't met your weekly quota). Overall I'd say this is a decent chess app.",
 "First I loved using this app but now from last 3-4 weeks I'm not able to login to my account. Even I have tried creating new account from different device and mail ID but still it isnt working. It is showing 'this site can't' be reached plz help me. As my 1800 rated account which is about 1 and half year old is very important for me. Or just help me make new I'd as I'm unable to do that also. I hope u understand my problem and help me with that. If this didn't happened I would give u 5 stars.",
 "Too much of the content is locked behind a time gate. One beginner's lesson per week doesn't make me want to pony up for a subscription-it makes me want to look somewhere else to learn the game. The value of this app is the free platform for playing random opponents, but there are other apps that do the same. I like the interface better than other apps I've tried, but that's just a preference, not a recommendation.",
 "so many people just sign in on two devices so they can abuse the master level computer to give them the best moves in an online match. i'm literally skill level 150 how is everyone at my level and below it capable of making a game end in 4-5 moves? that's not beginner level skill that's people cheating. if this could detect when people sign onto multiple devices to prevent this kind of abuse I would rate higher.",
 "Want to do anything other than a normal chess game for more than 2 minutes? Want more than 3 rated puzzles daily? Well better cough up that subscription cost because everything is locked behind a paywall if you want to do anything else in the app for more than a few minutes each day. But it's 5 puzzles you say? Nope, the 5th puzzle doesn't give you rating if you get it right, but if you're wrong bye bye to 15 rating. So essentially 3 rated puzzles daily...",
 "Great platform for chess, yet the limitations making it so you can only do an analysis once a day, and only do lessons once a week among other things that are limited to premium, I'm perfectly fine with the idea of premium, but I feel the limitations should be reduced at least a bit",
 "Network connection is more stable and it's much more responsive than the pwa but I've experienced two issues: 1. Game is abandoned after losing connection for hardly 5 seconds. 2. When trying out different moves in the analysis section, it shows every move as excellent even when you blunder or make the move suggested as the best. In the latter it then shows a different move as best. Because of these, I prefer to play on the browser on my computer instead",
 "Great app. But it's big time killer. It's terrible addiction. I wasted thousands of hours playing chess. I start playing even when I am in bathroom or driving and stopped in a signal. My gf left me because I wasn't able to give her time as I was addicted to chess. I almost lost of my job as I was playing chess while attending a official meeting. One good feature could be to add max limit on number of games played per day per person . Possible ?",
 'This is really a good game but the frustrating part of the game is everytime there is a draw when there is lot of time left. In my last game, I have checkmate the opponent and approx 10 minutes of the time were left but still you people declared it as a draw just after my move. This is completely ridiculous.',
 "Chess. *Needs no introduction* It is literally chess, but you can play online, or against a bot of your choice of difficulty. Additionally, there are daily puzzles and other weird, extra things. I suppose, if you dont like chess, then don't get it, if you do, this is a great option.",
 "Update :- And now sometimes when it's opponent's turn , and they don't make any move for sometimes.. instead of their countdown my timer is running out of time ..and as it's not my turn I can't make any move but my countdown still running till I am out of time...Weird!!!! So Rating Updated from 3 to 1. Original :- Sometimes countdown timer and gameplay itself freezes..",
 "Very nice chess up with a wealth of mini games,puzzles and challenged to go with it. I'm still quite new to it but I already see nice integration with twitch for live chess streams and reporting, made it very easy for me and my girlfriend to get into playing this lovely game.",
 "Not bad at all, you can change the theme, the pieces and everything. But right now I'm dealing with just one problem so here's my story. So a few days ago I learned a few new openings and I wanted to test them out so I tried to play an unrated game playing as black but I couldn't because it kept looking for someone to play with no matter how long I wait. I have been facing this issues for a really long time and it's still not fixed. Please look into it if possible ;)",
 "The app is decent, although I am quite suspicious that on lower levels (and I am lower level), people will sometimes use computer assisted moves. It's a bit frustrating to know when an idiot such as myself plays another idiot and then suddenly out of the blue the said idiot happens to perform three or four moves that are perfect and completely turn the tide of the game. It's like beginner on piano learning twinkle twinkle and then suddenly busting out a small sequence of Vivaldi's four seasons.",
 "It's a great chess apps but it's too sensitive to touch that often wrong move is registered. Also it's has a lot of bugs recently. The points system keep appearing then disappearing. Gone from excellent to worse. Luckily I didn't pay subscription.",
 'Very very worst. Am see many more time am give a checkmate. But my remaining times are run for opponent. So, fianlly win for opponent. Time out for me. This is look for many more match. And this is not a online game this is fully systematic game. Opp for sysytem player. Very cheat and fake',
 "Amazingly optimal app for anyone who I'd trying to learn chess, knows how to play and wants to okay on the go, or even for any pros who havent played in a while. it allows anyone and everyone at any skill level to improve and enjoy customizable games and options on the go for f r e e, with a free account of course, although the free account is just enough I believe and the premium isnt needed",
 "Great chess platform and enjoy the themes and accessibility. Request: The match should update while you're viewing it. Bug: I've noticed when starting a match with a friend, it will not show up until you restart the app.",
 "Drains an insane amount of battery when in use. AI not very fun to play against will do whatever it can to force a draw whenever it starts to loose, very irritating. Response to review: I'm not questioning the legality of the moves, but the style of play of the AI, it's very unsportsmanlike and makes it not very fun to play against. After trying an alternative app, that one both doesn't make my phone melt/drain tons of battery, the opponent resigns when they should instead of forcing draws!",
 "Best chess app I've ever played, worth subscribing just for unlimited analysis. If not then you can still learn loads and improve. Best part is analysing games aftwerwards, tells you where you made mistakes, attacks/defends that can be made. Only issue is computer not understanding tactical play but then most chess computers will be the same",
 'A very good chess app. You can play people from all over the world, do puzzles (limited if you have a free account), and even play a few bots. You can also analyze your games and see where you made mistakes.',
 "I think this is the best platform to play chess online . It's sound effects are amaging . We are not bored with this game . But it don't have bughouse , crazyhouse chess etc. But no problem .",
 "I love this app. It's a bit laggy sometimes, and the chat function ends when the game ends, which I find irritating. But it's free and fun. one thing I'd change is to make it less easy to unintentionally begin an online game with a stranger. I find I do this quite often, then have to abort the game.",
 'Add an option to disable "click twice to move a piece" (NOT "confirm each move"). I just want to move my pieces by dragging them across the board without having to worry about a misclick causing me to move a piece on accident.',
 "the personal game stats could be more descriptive. include wins and or losses by checkmate time out, or resign. the information is already there & it would be a great training tool. example: win or loss records by checkmate could analyze if your tactics are good or poor. win or loss records by time out could analyze if your end game strategy is good or poor. win or loss records by resign could analyze if you're giving up too early or winning too easily. ave. opponent rating exists",
 "They have twice now tried to sign me up for premium while I was asleep. I had premium for a little bit and then wasn't playing enough to warrant the price. Since I deactivated it they have tried to secretly re-activate it on my dead account first and now just tonight on my newest yet still hardly used account. I thought it was just a mistake last time, but this seems shady as hell now.",
 'The AI players are buggy with the rules. One instance is where it checks the king with the queen in the first 4 moves of the game and instantly declares itself the winner, if you duplicate the moves it counters the capture with the knight and the game plays on.',
 'worst chess app. i have lost atleast 300 rating points because of connection problem. i know many others players are also having this problem. This problem is worst then you try to play bullet games. Even premoves takes 2 to 10 or 20 socends atmost of the time and this is not my internet connection problem.',
 "The lag time is absolutely horrible a lot of the time. It's not possible to play a game in 1 minute mode. The app should be able to tell when a move is made. Lots of forum talk but nothing is ever done. Yes lag time but sometimes time is put BACK on opponents timer. Absolutely ridiculous!",
 "It's the best chess game as we are having rated bots, easy to use this app, you can start lessons to study about chess, it has many varients, you can play puzzle to know more about tactics. The best thing is that chess improves maths I love this game",
 'This app is good for players. And this makes fun too. The only thing is the SUBSCRIPTION. This app makes to solve 3 puzzles a day. But after subscription the app makes Unlimited puzzles a day. And plz editors, make this app a little bit easier for students to learn chess without a subscription. Thanks.',
 'Smooth gameplay. Good pairing system(you can also challenge your friends). Bots and pass-and-play for playing offline (with different difficulty level bots). All for free (no in-game purchases, though there is a paid premium). Overall, the best chess app in Google Play.']

'''
